@host = https://localhost
@port = 7133
@token = CfDJ8NNIWtzFBL1OmKKH1Pn4YSJz_JmIyxrIAq8JKGB_nb8OHne57xeRdMNyZaWQFevbUTenk264vQynDoLFZKTChox73mMC6jhe_wqq1oRUeNKoWXFWjdIToyqp9dOm1s-0VcXDRWIMizO976JjQ7EFhHaIjuVbzIZW6OOQ_Zkh4WJOJUUWmeiIy2VQdNwEiKbW_Kw1J1oIfMiPsygRjCAie3qPo996N3yvwaw3ZWOSE8FTHLhcQHlbgzCesoU15UX3rYM4E5oTU5fgKnCuBM3BBHBPLwdyMr7uIs0HZ_qFuN4G5JtRilheOJtyHFnapNK1mQM6emq6OB6PKuZ0fr9oSAFToGyA2KFdeGIcgNVknFW7EGQpUwgecIBhv-mY68Ks9_pKOZ4VD5h_QLa6eXlw5b2vI2rCSRwsMextMPG2_cvcRNNufipvuYfmCcCU5oWq9mQUnqari98ZnC-shVZTndbAgY_ht1sA4Kb81aPpET4XHIhBnq9MItcrN00TVqT28triyBqOJ4bwFXZqHkaz9uygCZuD-AiOmzsLgOFqSr5jhWLhVfK6S_vb3fcVjypFjs3PJyGQT_acs79gcmZUvkq39UT0UgCoFIeWbPdX8F6vmoIziPh6PtQVgiWI36OtyJ_KCMvKgbeRJyLClPoRmUx4UjUra2Xx8RKJN5dkheGk0kTHYt827xlMr-9zvxI2m3wWMMKJ2_7SkeZsBNaUvTe5HqfzHRxlNUzNgyPS0Rl1mWFse-OL_sbrTybzd6lUhlVdcuX5A4KweuURAWOYuqlXZqWkm9A5Z1H2NUlI1Z2V

@Restaurants.API_HostAddress = https://localhost:7133
###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/2
Authorization: Bearer {{token}}
###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/145

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Spicy Delights",
  "Description": "A culinary experience like no other",
  "Category": "Fine Dining",
  "HasDelivery": true,
  "ContactEmail": "info",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54321"
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Spicy Delights",
  "Description": "A culinary experience like no other",
  "Category": "Greek",
  "HasDelivery": true,
  "ContactEmail": "info@gourmedelights.com",
  "ContactNumber": "+30-2105777762",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-321"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/7
Content-Type: application/json

{
  "Name": "Spicy Delights",
  "Description": "A culinary experience like no other",
  "HasDelivery": false
}

###
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/99
Content-Type: application/json

{
  "Name": "Spicy Delights",
  "Description": "A culinary experience like no other",
  "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCaleries": 750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/1/dishes/2

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "Password1!"
}